<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "evchat"
 *
 * Auto generated by Extension Builder 2014-07-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Visitor chat',
	'description' => 'Support your visitors/customers with a live AJAX chat!',
	'category' => 'plugin',
	'author' => 'Vlatko Šurlan',
	'author_email' => 'vlatko.surlan@evorion.hr',
	'author_company' => 'Evorion mediji j.d.o.o.',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>